### ISSUE TITLE
Exception in thread "main" java.lang.AssertionError

### ISSUE THREAD

**Issue by jm2285** [shillem/dataloader-docker#1]
Hi Shillem
I am getting Exception in thread "main" java.lang.AssertionError when trying to build your project on a Linux container. Tried Win 10 and Ubuntu's latest build with the same results. I thought you may want to take a look

**Comment by shillem** [comment]
Hello, thank you for bringing it to my attention. Building the project with the latest official dataloader repository commit throws the error. Instead, if I build it using with their latest tag it works.
I changed the Dockerfile to clone and check out the latest tag rather than simply using the latest commit. It should work for you now too.

**Comment by jm2285** [comment]
Hello Shillem, It does build now with no issues, thank you!. I do however see an error when running the container and was wondering if it's due to not having anything scheduled on jobber yet.
$ docker run <image_name>
Listening for commands on /var/jobber/1000/cmd.sock
yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `version...` into struct { Version jobfile.SemVer "yaml:\"version\""

**Comment by shillem** [comment]
Good!

Regarding your other issue, as I documented in the readme there are 2 ways in which you can run the docker: depending on the arguments passed, either as a command or as a scheduler.

Launching `docker run` without overriding the `--entrypoint` will instantiate the scheduled one. At this point you must map a valid jobber file to instruct jobber on what to do when the container starts it (`-v $(pwd)/jobber.yaml:/home/dataloader/.jobber`). See the last example in the readme.
